import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Image from 'next/image';
import Banner from '../components/banner/Banner';
import { ReduxProvider } from '@/state/ReduxProvider';
import { Toaster } from 'sonner';

const inter = Inter({ variable: '--font-inter', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="relative flex min-h-screen flex-col text-primary subpixel-antialiased">
        <ReduxProvider>
          <Image
            src="/assets/mainBg.jpg"
            alt=""
            quality={80}
            fill
            sizes="100vw"
            priority
            className="-z-10 bg-fixed object-cover"
          />
          <Banner />
          <div className="h-screen w-screen overflow-y-scroll">{children}</div>
          <Toaster
            richColors
            position="top-center"
            expand={true}
            className="flex justify-center"
            toastOptions={{
              className: '!w-auto',
            }}
          />
        </ReduxProvider>
      </body>
    </html>
  );
}
